# Generated by Django 4.2 on 2023-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('채소류', '채소류'), ('과일류', '과일류'), ('샐러드', '샐러드'), ('버섯류', '버섯류')], default='채소류', max_length=4),
        ),
    ]
