# Generated by Django 4.2 on 2023-06-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private_price',
            field=models.PositiveIntegerField(default=0, verbose_name='개인구매 가격'),
        ),
        migrations.AddField(
            model_name='project',
            name='public_price',
            field=models.PositiveIntegerField(default=0, verbose_name='공동구매 가격'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('채소류', '채소류'), ('과일류', '과일류'), ('샐러드', '샐러드'), ('버섯류', '버섯류')], max_length=4),
        ),
    ]
