# Generated by Django 4.2 on 2023-06-06 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crop', '0003_project_private_price_project_public_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cnt_supporter',
            field=models.PositiveIntegerField(default=0, verbose_name='후원자 수'),
        ),
        migrations.AddField(
            model_name='project',
            name='cur_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='모인금액'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal_amount',
            field=models.PositiveIntegerField(verbose_name='목표금액'),
        ),
        migrations.AlterField(
            model_name='project',
            name='private_price',
            field=models.PositiveIntegerField(verbose_name='개인구매 가격'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_price',
            field=models.PositiveIntegerField(verbose_name='공동구매 가격'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.project')),
            ],
        ),
    ]
