# Generated by Django 3.2 on 2023-06-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0010_alter_comment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='private_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='public_price',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('채소류', '채소류'), ('과일류', '과일류'), ('버섯류', '버섯류'), ('축산물', '축산물'), ('쌀/잡곡/견과류', '쌀/잡곡/견과류'), ('수산물/건해산물', '수산물/건해산물')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='publicprice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.project'),
        ),
        migrations.AddField(
            model_name='privateprice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.project'),
        ),
    ]
