# Generated by Django 3.2 on 2023-07-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0011_auto_20230629_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateprice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_prices', to='crop.project'),
        ),
        migrations.AlterField(
            model_name='publicprice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_prices', to='crop.project'),
        ),
    ]
