apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: seolhuigwan/crop-swipe-api:latest
        ports:
        - containerPort: 8000
        limits:
          