pipeline{
    environment{
        IMAGE_NAME = "seolhuigwan/crop-swipe-api" // docker hub id / repository 이름
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-key')
    }
    agent any
    stages{
        stage('==== pull codes from github ===='){
            steps{
                checkout scm
            }
        }
        stage("==== build docker image by dockerfile ===="){
            steps{
                sh'''
                    cd cropswipe
                    ls -al
                    cat Dockerfile
                '''
                script{
                    docker.build("${IMAGE_NAME}:${BUILD_NUMBER}")
                }
            }
            post{
                success{
                    echo "Success Dockerizing Crop-Swipe"
                }
                failure{
                    error "Fail Dockerizing Crop-Swipe"
                }
            }
        }
        stage("==== docker login ===="){
            steps{
                script{
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                }
            }
            post{
                success{
                    echo "Success Login"
                }
                failure{
                    error "Failure Login"
                }
            }
        }
        stage("==== upload to docker hub ===="){
            steps{
                script{
                    sh 'docker push $IMAGE_NAME:$BUILD_NUMBER'
                }
            }
            post{
                success{
                    echo "Success Upload"
                }
                failure{
                    error "Failure Upload"
                }
            }
        }
    }
}