pipeline{
    environment{
        IMAGE_NAME = "seolhuigwan/crop-swipe-api" // docker hub id / repository 이름
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-key')
    }
    agent any
    stages{
        stage('==== pull codes from github ===='){
            steps{
                checkout scm
            }
        }
        stage("==== build docker image by dockerfile ===="){
            steps{
                script{
                    sh'''
                        cd cropswipe/
                        ls -al
                        docker build --tag $IMAGE_NAME:$BUILD_NUMBER .
                    '''
                }
            }
            post{
                success{
                    echo "Success Dockerizing Crop-Swipe"
                }
                failure{
                    error "Fail Dockerizing Crop-Swipe"
                }
            }
        }
        stage("==== docker login ===="){
            steps{
                script{
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                }
            }
            post{
                success{
                    echo "Success Login"
                }
                failure{
                    error "Failure Login"
                }
            }
        }
        stage("==== upload to docker hub ===="){
            steps{
                script{
                    sh 'docker push $IMAGE_NAME:$BUILD_NUMBER'
                }
            }
            post{
                success{
                    echo "Success Upload"
                }
                failure{
                    error "Failure Upload"
                }
            }
        }
        stage("==== update yaml file ===="){
            steps{
                script{
                    sh"""
                        ls -al
                        sed -i 's/\${BUILD_NUMBER}/${env.BUILD_NUMBER}/g' ./api-deploy.yaml
                        git config --global user.email "shg5977@naver.com"
                        git config --global user.name "SeolHuiGwan9478"
                        git pull origin master
                        git add .
                        git status
                        git commit -m 'update the image tag'
                        git remote -v
                        git push -u origin master
                    """
                }
            }
        }
    }
}